# Generated by Django 5.0.1 on 2024-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=8)),
                ('PLAD', models.CharField(max_length=32)),
                ('CLAD', models.CharField(max_length=32)),
                ('TLAD', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=32)),
                ('restaurant_address', models.CharField(max_length=128)),
                ('restaurant_open_time', models.DateTimeField()),
                ('restaurant_close_time', models.DateTimeField()),
                ('location', models.CharField(max_length=128)),
                ('more', models.TextField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=32)),
                ('site_address', models.CharField(max_length=128)),
                ('site_open_time', models.DateTimeField()),
                ('site_close_time', models.DateTimeField()),
                ('location', models.CharField(max_length=128)),
                ('more', models.TextField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('ID', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=2)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
