# Generated by Django 5.0.1 on 2024-01-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyyf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ID',
            new_name='UID',
        ),
    ]
