# Generated by Django 5.0.1 on 2024-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyyf', '0002_rename_id_userinfo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='more',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='more',
            field=models.TextField(default=None),
        ),
    ]
