# Generated by Django 5.0.1 on 2024-01-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyyf', '0003_userinfo_more_alter_site_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='CLAD',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='city',
            name='PLAD',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='city',
            name='Province',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='city',
            name='TLAD',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='more',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_close_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_open_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='score',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_address',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_close_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_open_time',
            field=models.DateTimeField(default=None),
        ),
    ]
